Repository openshift/cluster-api-provider-agent, pull requests merged in 2022-04, with the labels that each got.

#41 MGMT-9821: Add Conditions to AgentMachines
  api/v1alpha1/agentmachine_types.go
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
  vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/agentmachine_types.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/util/conditions/doc.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/getter.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/matcher.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/matchers.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/merge.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/merge_strategies.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/patch.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/setter.go
  vendor/sigs.k8s.io/cluster-api/util/conditions/unstructured.go
Labels: size/XXL, approved, lgtm

#45 MGMT-9946: Avoid unnecessary requeues in agent cluster controller
  controllers/agentcluster_controller.go
  controllers/agentcluster_controller_test.go
  controllers/agentmachine_controller.go
Labels: size/M, approved, lgtm

#46 NO-ISSUE: fixing some typos in the README
  README.md
Labels: size/XS, approved, lgtm
