Repository openshift/cluster-api-provider-agent, pull requests merged in 2022-09, with the labels that each got.

#54 MGMT-10968: Replace agentmachine finalizer with machine pre-delete hook
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentclassification_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
  vendor/github.com/openshift/assisted-service/models/cluster_network.go
  vendor/github.com/openshift/assisted-service/models/connectivity_check_nic.go
  vendor/github.com/openshift/assisted-service/models/container_image_availability_request.go
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/models/disk_skip_formatting_params.go
  vendor/github.com/openshift/assisted-service/models/domain_resolution_request.go
  vendor/github.com/openshift/assisted-service/models/download_boot_artifacts_request.go
  vendor/github.com/openshift/assisted-service/models/drive_type.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/host_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/models/interface.go
  vendor/github.com/openshift/assisted-service/models/inventory.go
  vendor/github.com/openshift/assisted-service/models/machine_network.go
  vendor/github.com/openshift/assisted-service/models/next_step_cmd_request.go
  vendor/github.com/openshift/assisted-service/models/node_label_params.go
  vendor/github.com/openshift/assisted-service/models/os_image.go
  vendor/github.com/openshift/assisted-service/models/ovirt_platform.go
  vendor/github.com/openshift/assisted-service/models/platform.go
  vendor/github.com/openshift/assisted-service/models/release_image.go
  vendor/github.com/openshift/assisted-service/models/route.go
  vendor/github.com/openshift/assisted-service/models/service_network.go
  vendor/github.com/openshift/assisted-service/models/step.go
  vendor/github.com/openshift/assisted-service/models/step_type.go
  vendor/github.com/openshift/assisted-service/models/tang_connectivity_request.go
  vendor/github.com/openshift/assisted-service/models/tang_connectivity_response.go
  vendor/github.com/openshift/assisted-service/models/upgrade_agent_request.go
  vendor/github.com/openshift/assisted-service/models/upgrade_agent_response.go
  vendor/github.com/openshift/assisted-service/models/upgrade_agent_result.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#55 Cleanup
  Makefile
  controllers/agentmachine_controller.go
  main.go
Labels: size/M, approved, lgtm

#57 Set user maneged networking to true in the agentCluster agentClusterInstall
  controllers/agentcluster_controller.go
  controllers/agentcluster_controller_test.go
Labels: size/XS, approved, lgtm
