Repository openshift/cluster-api-provider-agent, pull requests merged in 2024-09, with the labels that each got.

#138 OCPBUGS-32592: Adjust controllers to handle backup and restore
  controllers/agentcluster_controller.go
  controllers/agentcluster_controller_test.go
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/util/patch/doc.go
  vendor/sigs.k8s.io/cluster-api/util/patch/options.go
  vendor/sigs.k8s.io/cluster-api/util/patch/patch.go
  vendor/sigs.k8s.io/cluster-api/util/patch/utils.go
Labels: size/XL, approved, lgtm, jira/valid-bug, jira/valid-reference

#140 OCPBUGS-32592: Ensure Agent isn't unbound if paused
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#142 NO-ISSUE: Ignore not found error when finding ClusterDeployment
  controllers/agentcluster_controller.go
  controllers/agentmachine_controller.go
Labels: size/XS, approved, lgtm, jira/valid-reference

#143 [release-ocm-2.11] OCPBUGS-42390: Backup and restore fixes
  controllers/agentcluster_controller.go
  controllers/agentcluster_controller_test.go
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/util/patch/doc.go
  vendor/sigs.k8s.io/cluster-api/util/patch/options.go
  vendor/sigs.k8s.io/cluster-api/util/patch/patch.go
  vendor/sigs.k8s.io/cluster-api/util/patch/utils.go
Labels: size/XL, approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#146 MGMT-18606: Update to Go 1.21
  Dockerfile
  Dockerfile.rhtap
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, approved, lgtm, jira/valid-reference

#148 NO-ISSUE: Fix agent cluster controller orphaning tests
  controllers/agentcluster_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference
