Repository openshift/cluster-api-provider-agent, pull requests merged in 2024-06, with the labels that each got.

#106 Create Dockerfile.rhtap
  Dockerfile.rhtap
Labels: approved, size/S, lgtm

#111 Konflux enablement
  .tekton/cluster-api-provider-agent-mce-25-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-25-push.yaml
  Dockerfile.rhtap
  Makefile
Labels: size/XL, approved, lgtm

#108 Updated to point to correct Dockerfile
  .tekton/cluster-api-provider-agent-mce-25-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-25-push.yaml
Labels: size/XS, approved, lgtm

#113 Konflux enablement for main branch
  Dockerfile.rhtap
Labels: approved, size/S, lgtm
