Repository openshift/cluster-api-provider-agent, pull requests merged in 2024-10, with the labels that each got.

#144 [release-ocm-2.10] OCPBUGS-42608: Backup and restore fixes
  controllers/agentcluster_controller.go
  controllers/agentcluster_controller_test.go
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/util/patch/doc.go
  vendor/sigs.k8s.io/cluster-api/util/patch/options.go
  vendor/sigs.k8s.io/cluster-api/util/patch/patch.go
  vendor/sigs.k8s.io/cluster-api/util/patch/utils.go
Labels: size/XL, approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#149 MGMT-18689: Add schemes when remote client is created
  controllers/remote_client.go
Labels: size/XS, approved, lgtm, jira/valid-reference

#150 [ACM 2.12] MGMT-19137: Add schemes when remote client is created
  controllers/remote_client.go
Labels: size/XS, approved, lgtm
