Repository openshift/cluster-api-provider-agent, pull requests merged in 2025-05, with the labels that each got.

#215 ci: Make the builds hermetic and build source
  .tekton/cluster-api-provider-agent-mce-29-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-29-push.yaml
Labels: approved, size/S, lgtm

#214 NO-ISSUE: Prevent further reconciling after removing AgentMachine finalizer
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#218 Trigger konflux build
  .tekton/cluster-api-provider-agent-mce-29-pull-request.yaml
Labels: size/XS, approved, lgtm

#219 Konflux multi-arch fix
  .tekton/cluster-api-provider-agent-mce-29-pull-request.yaml
  Dockerfile.rhtap
Labels: size/XS, approved, lgtm
