Repository openshift/cluster-api-provider-agent, pull requests merged in 2025-08, with the labels that each got.

#283 NO-ISSUE: Use common pipeline reference from stolostron repo
  .tekton/cluster-api-provider-agent-mce-210-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-210-push.yaml
Labels: size/XXL, approved, lgtm, jira/valid-reference

#287 Fixing EC violations
  .tekton/cluster-api-provider-agent-mce-29-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-29-push.yaml
Labels: size/XXL, approved, lgtm

#288 [release-ocm-2.13] MGMT-21270: Configure files to enable Konflux
  .tekton/cluster-api-provider-agent-mce-28-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-28-push.yaml
  Dockerfile.rhtap
Labels: approved, size/L, jira/valid-reference

#289 NO-ISSUE: Update renovate.json
  renovate.json
Labels: approved, size/S, jira/valid-reference
