Repository openshift/cluster-api-provider-agent, pull requests merged in 2025-03, with the labels that each got.

#170 MGMT-19762: Don't use a disconnected Agent
  config/crd/bases/capi-provider.agent-install.openshift.io_agentmachines.yaml
  controllers/agentmachine_controller.go
  controllers/agentmachine_controller_test.go
Labels: size/M, approved, lgtm, jira/valid-reference

#181 [release-ocm-2.12] ACM-18941: CVE-2025-22868 x/oauth2 => golang-oauth2 v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, jira/valid-reference

#184 [release-ocm-2.9] ACM-18173: CVE-2025-22868 x/oauth2 => golang-oauth2 v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, jira/valid-reference

#182 [release-ocm-2.13] ACM-18942: CVE-2025-22868 x/oauth2 => golang-oauth2 v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, jira/valid-reference

#179 ACM-18989: CVE-2025-22868 x/oauth2 => golang-oauth2 v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, jira/valid-reference

#183 [release-ocm-2.10] ACM-18939: CVE-2025-22868 x/oauth2 => golang-oauth2 v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, jira/valid-reference

#180 [release-ocm-2.11] ACM-18940: CVE-2025-22868 x/oauth2 => golang-oauth2 v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, jira/valid-reference

#189 [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, jira/valid-reference

#188 NO-ISSUE: Remove eran ifrach account from OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, jira/valid-reference

#192 [release-ocm-2.10] NO-ISSUE: Update OWNERS
  OWNERS
Labels: approved, size/S, lgtm, jira/valid-reference

#193 [release-ocm-2.9] NO-ISSUE: Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, jira/valid-reference
