Repository openshift/cluster-api-provider-agent, pull requests merged in 2025-09, with the labels that each got.

#291 NO-ISSUE: Fix pull request tekton file formatting
  .tekton/cluster-api-provider-agent-mce-210-pull-request.yaml
Labels: size/XS, approved, jira/valid-reference

#292 [release-ocm-2.13] NO-ISSUE: Fix annotations for tekton files
  .tekton/cluster-api-provider-agent-mce-28-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-28-push.yaml
Labels: size/XS, approved, jira/valid-reference

#293 [release-ocm-2.11] NO-ISSUE: Fix annotations for tekton files
  .tekton/cluster-api-provider-agent-mce-26-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-26-push.yaml
Labels: size/XS, approved, lgtm, jira/valid-reference

#284 [release-ocm-2.14] NO-ISSUE: Use common pipeline reference from stolostron repo
  .tekton/cluster-api-provider-agent-mce-29-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-29-push.yaml
Labels: size/XXL, approved, jira/valid-reference

#296 NO-ISSUE: No-op push to rebuild
  README.md
Labels: size/XS, approved, jira/valid-reference

#297 NO-ISSUE: Correct renovate config
  renovate.json
Labels: approved, size/S, jira/valid-reference

#335 [release-ocm-2.13] NO-ISSUE: Fix ACM 2.13/MCE 2.8 tekton files.
  .tekton/cluster-api-provider-agent-mce-28-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-28-push.yaml
Labels: size/M, approved, jira/valid-reference

#334 chore(KONFLUX-6210): fix and set name and cpe label for cluster-api-provider-agent-mce-29
  Dockerfile.rhtap
Labels: size/XS, approved, lgtm

#336 [release-ocm-2.13] NO-ISSUE: Add missing pre-fetch input field to tekton files
  .tekton/cluster-api-provider-agent-mce-28-pull-request.yaml
  .tekton/cluster-api-provider-agent-mce-28-push.yaml
Labels: size/XS, approved, jira/valid-reference

#388 NO-ISSUE: Update README to trigger konflux run
  README.md
Labels: size/XS, approved, jira/valid-reference

#395 NO-ISSUE: Update renovate to only update dependencies for master branch
  renovate.json
Labels: approved, size/S, jira/valid-reference
